name: Ubuntu Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Install Git
        run: sudo apt-get install -y git
      - name: Install autotools and related packages
        run: |
          sudo apt-get install -y autotools-dev autoconf automake libtool-bin pkg-config texinfo
          sudo apt-get install -y libxslt1.1 docbook-utils docbook-xsl
          sudo apt-get install -y gettext autopoint rake
      - name: Install Yasm and related packages
        run: sudo apt-get install -y yasm gperf
      - name: Install CMake and related packages
        run: sudo apt-get install -y cmake ninja-build
      - name: Install Python3 and related packages
        run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          pip3 install progressbar2 requests PyYAML
      - name: Install Rust and related packages
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env
          sudo apt-get install -y libssl-dev libevent-dev libffi-dev libglib2.0-dev libjpeg-dev libpng-dev libtiff-dev libgtk-3-dev libncurses-dev libudev-dev libusb-dev libavformat-dev libswscale-dev libavcodec-dev libavutil-dev libtool
      - name: Install additional packages
        run: sudo apt-get install -y subversion flex bison patch mercurial docbook-to-man rst2pdf libisl-dev po4a p7zip-full p7zip gyp
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run cross_compile.py script
        run: ./cross_compiler.py -p mpv,ffmpeg_extra
