on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Install Git
        run: sudo apt-get install -y git
      - name: Install autotools and related packages
        run: |
          sudo apt-get install -y autotools-dev autoconf automake libtool-bin pkg-config texinfo
          sudo apt-get install -y libxslt1.1 docbook-utils docbook-xsl
          sudo apt-get install -y gettext autopoint rake
      - name: Install Yasm, Nasm and related packages
        run: sudo apt-get install -y yasm nasm gperf
      - name: Install CMake and Ninja
        run: sudo apt-get install -y cmake ninja-build
      - name: Install Python3 and related packages
        run: |
          sudo apt-get install -y python3 python3-dev python3-pip
          pip3 install progressbar2 requests PyYAML
      - name: Install Rust and related packages
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y && source $HOME/.cargo/env
      - name: Install additional packages
        run: |
          sudo apt-get install -y subversion cvs pax patch mercurial gettext autopoint docbook-to-man rst2pdf po4a
          sudo apt-get install -y libisl-dev libtool-bin
          sudo apt-get install -y p7zip-full p7zip gyp
      - name: Install latest version of Meson
        run: |
          git clone https://github.com/mesonbuild/meson.git
          cd meson
          python3 setup.py build
          sudo python3 setup.py install
          cd ..
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run cross_compile.py script
        run: ./cross_compiler.py -p mpv,ffmpeg_extra
